#!/usr/bin/env bash

docker run \
  -u $(id -u):$(id -g) \
  -v ~/.aws:/aws \
  -v $(pwd):$(pwd) \
  --workdir $(pwd) --rm -it \
  -e AWS_CONFIG_FILE=/aws/config \
  -e AWS_SHARED_CREDENTIALS_FILE=/aws/credentials \
  -e AWS_DEFAULT_REGION \
  -e AWS_ACCESS_KEY_ID \
  -e AWS_SECRET_ACCESS_KEY \
  -e AWS_PROFILE \
  -e AWS_ROLE_ARN \
  -e AWS_WEB_IDENTITY_TOKEN_FILE \
  -e AWS_ROLE_SESSION_NAME \
  -e AWS_SESSION_TOKEN \
  -e KUBECONFIG=$(pwd)/aws/.kube/config \
  amazon/aws-cli:latest \
  "$@"